name:                gtk-intro
version:             0.1.0.0
github:              "markxnelson/haskell-playground/gtk-intro"
license:             Other
author:              "Mark Nelson"
maintainer:          "mark.x.nelson@gmail.com"
copyright:           "2020 Mark Nelson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/markxnelson/haskell-playground/gtk-intro#readme>

dependencies:
- base >= 4.7 && < 5
- gi-gtk
- haskell-gi-base
- haskell-gi-overloading >= 1.0

library:
  source-dirs: src

executables:
  gtk-intro-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gtk-intro

tests:
  gtk-intro-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gtk-intro
